### ISSUE TITLE
sass-autocompile isn't compiling

### ISSUE THREAD

**Issue by juliesunset** [armin-pfaeffle/sass-autocompile#106] opened 2017-02-06 15:46 UTC
I installed sass-autocompile last week, and it worked very well at that time.

I open my Atom this morning, sass-autocompile doesn't work. It tells me that the compilation start, but never finishes the procedure.
"Compilation Error
Compilation canceled due to timeout (300000 ms) "

I haven't changed anything in my system.

**Comment by armin-pfaeffle** [comment] 2017-02-06 22:04
Hey! I think your code has an infinite loop. Can you try a really simple example, only using one file like this:
```sass
// compileCompressed: ./style.min.css
body{
    background-color: red;
}
```

**Comment by juliesunset** [comment] 2017-02-07 14:24
Thank you for your reply.
I tried your suggestion, but the problem remains.

**Comment by armin-pfaeffle** [comment] 2017-02-08 09:45
Can you try to compile a SASS/SCSS file on your own? Exceute the following steps:
- Create a file `style.scss`
- Put this as content:
```
$background-color: red;
body{
    background-color: $background-color;
}
```
- Open terminal and browse to the path where `style.scss` is placed
- Execute this command: `node-sass style.scss style.css`
This is my output:
```
D:\tmp>node-sass style.scss style.css
Rendering Complete, saving .css file...
Wrote CSS to D:\tmp\style.css

D:\tmp>
```
What is yours? 

Furthermore, can you give mit your settings for my package? Perhaps there is the problem.

**Comment by juliesunset** [comment] 2017-02-08 14:23
I am not very familiar with the terminal, so I can't say if I did correctly what you told me ... besides, it doesn't appear to work ...

About my package settings
Compile on Save : ON -> but doesn't seem to work
Show compile SASS item in tree View context menu : ON
Compile with expanded output style : ON
Filename pattern for expanded compiled files: ../css/$1.css
indent type : tab
Indent width : 4
Linefeed : lf
Include paths : ../css/sass/
Show Sart compiling notification : ON
Show additional compilation info : ON
Show warning when using ol paramters : ON
node-sass execution timeout : 100000

**Comment by armin-pfaeffle** [comment] 2017-02-09 22:08
I could reproduce the problem! I will find a solution!

**Comment by armin-pfaeffle** [comment] 2017-02-10 00:21
I published version 0.13.3 right now. Please update to this version and try again. Now this issue should be fixed, so I close it now.

**Closed by armin-pfaeffle** 2017-02-10 00:21 UTC

**Comment by juliesunset** [comment] 2017-02-13 14:43
It's work now! thank you!

**Comment by AdiBev** [comment] 2019-01-20 02:41
Hi, I'm having the same issue as well except it says Compilation canceled due to timeout (10000 ms).
It works with cli without any problem. I have a few partials which I'm importing into main.scss file. It was working fine for a long time until now. Thank you.
